// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Ping command — proves the tauri-specta IPC pipeline end-to-end.
	 * 
	 *  Call from the frontend via:
	 *    import { commands } from '$lib/ipc';
	 *    const pong = await commands.ping(); // → "pong"
	 */
	ping: () => __TAURI_INVOKE<string>("ping"),
};

