// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Ping command — proves the tauri-specta IPC pipeline end-to-end.
	 * 
	 *  Call from the frontend via:
	 *    import { commands } from '$lib/ipc';
	 *    const pong = await commands.ping(); // → "pong"
	 */
	ping: () => __TAURI_INVOKE<string>("ping"),
	listTags: () => typedError<TagWithUsage[], string>(__TAURI_INVOKE("list_tags")),
	createTag: (name: string, color: string) => typedError<TagWithUsage, string>(__TAURI_INVOKE("create_tag", { name, color })),
	updateTag: (id: number, name: string, color: string) => typedError<TagWithUsage, string>(__TAURI_INVOKE("update_tag", { id, name, color })),
	deleteTag: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_tag", { id })),
	listBudgets: () => typedError<BudgetSummary[], string>(__TAURI_INVOKE("list_budgets")),
	getBudget: (id: number) => typedError<BudgetDetail, string>(__TAURI_INVOKE("get_budget", { id })),
	createBudget: (name: string, startDate: string, endDate: string, notes: string | null) => typedError<BudgetDetail, string>(__TAURI_INVOKE("create_budget", { name, startDate, endDate, notes })),
	updateBudget: (id: number, name: string, startDate: string, endDate: string, status: string, notes: string | null) => typedError<BudgetDetail, string>(__TAURI_INVOKE("update_budget", { id, name, startDate, endDate, status, notes })),
	deleteBudget: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_budget", { id })),
	duplicateBudget: (sourceId: number, name: string, startDate: string, endDate: string) => typedError<BudgetDetail, string>(__TAURI_INVOKE("duplicate_budget", { sourceId, name, startDate, endDate })),
	createRecord: (budgetId: number, type: string, emoji: string, label: string, amount: number, notes: string | null) => typedError<BudgetRecord, string>(__TAURI_INVOKE("create_record", { budgetId, type, emoji, label, amount, notes })),
	updateRecord: (id: number, emoji: string, label: string, amount: number, notes: string | null) => typedError<BudgetRecord, string>(__TAURI_INVOKE("update_record", { id, emoji, label, amount, notes })),
	deleteRecord: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_record", { id })),
	setRecordTags: (recordId: number, tagIds: number[]) => typedError<BudgetRecord, string>(__TAURI_INVOKE("set_record_tags", { recordId, tagIds })),
	getStatsSummary: (filter: StatsFilter) => typedError<StatsSummary, string>(__TAURI_INVOKE("get_stats_summary", { filter })),
	listRecordsByTag: (tagId: number) => typedError<TagRecord[], string>(__TAURI_INVOKE("list_records_by_tag", { tagId })),
	/**  Return the on-disk path of the SQLite database file. */
	getDbPath: () => typedError<string, string>(__TAURI_INVOKE("get_db_path")),
	/**
	 *  Dump all records to a CSV file at `path`.
	 * 
	 *  Columns: budget, budget_start, budget_end, type, emoji, label, amount, tags (semicolon-joined),
	 *  notes, is_adjustment.  The column order matches the import template so exports round-trip
	 *  cleanly through the Import from CSV flow.
	 */
	exportCsv: (path: string) => typedError<null, string>(__TAURI_INVOKE("export_csv", { path })),
	/**
	 *  Write the CSV import template (header + two example rows) to `path`.
	 * 
	 *  Column order: budget, budget_start, budget_end, type, emoji, label, amount, tags, notes.
	 *  (is_adjustment is omitted from the template — it's not needed for import.)
	 */
	exportCsvTemplate: (path: string) => typedError<null, string>(__TAURI_INVOKE("export_csv_template", { path })),
	/**
	 *  Parse a CSV file and return a preview grouped by budget for the user to review.
	 * 
	 *  The frontend renders the preview (accept/decline per record, inflow/outflow toggle)
	 *  and then passes the approved groups to `import_csv`.
	 */
	previewCsvImport: (path: string) => typedError<CsvImportPreview, string>(__TAURI_INVOKE("preview_csv_import", { path })),
	/**
	 *  Insert the user-approved CSV import groups into the database.
	 * 
	 *  Each group maps to one budget (created if new). Records, tags, and record_tags
	 *  are created in a single atomic transaction — any failure rolls back all changes.
	 */
	importCsv: (groups: CsvImportGroup[]) => typedError<ImportResult, string>(__TAURI_INVOKE("import_csv", { groups })),
	/**
	 *  Copy the raw SQLite database file to `dest`.
	 * 
	 *  Checkpoints the WAL first so recent writes are flushed into the main file
	 *  and the backup is complete and consistent.
	 */
	copyDb: (dest: string) => typedError<null, string>(__TAURI_INVOKE("copy_db", { dest })),
	/**
	 *  Validate a `.db` file as an Equilibrium backup, stage it, then restart the
	 *  app so the startup handler can swap it in before opening the live connection.
	 * 
	 *  Returns `Err` immediately on any validation or I/O failure — no restart
	 *  occurs and the live database is untouched. On success this function diverges
	 *  (the process restarts) and the `Ok` arm is never reached by the caller.
	 */
	stageRestore: (src: string) => typedError<null, string>(__TAURI_INVOKE("stage_restore", { src })),
	/**
	 *  Check for a pending restore outcome written by the startup handler and
	 *  consume it (deletes the sentinel file). Returns `Some` exactly once per
	 *  restore attempt, then `None` on all subsequent calls.
	 * 
	 *  Call this from the frontend `onMount` to surface a post-restart toast.
	 */
	takeRestoreStatus: () => typedError<{
	ok: boolean,
	message: string,
} | null, string>(__TAURI_INVOKE("take_restore_status")),
	/**  Permanently delete all budgets, records, tags, and record_tags. */
	resetAllData: () => typedError<null, string>(__TAURI_INVOKE("reset_all_data")),
	/**
	 *  Returns the best-matching emoji for a record label.
	 *  Falls back to "📝" if no confident match.
	 *  The backend is swappable — see `src-tauri/src/emoji/mod.rs`.
	 */
	autoSuggestEmoji: (label: string) => __TAURI_INVOKE<string>("auto_suggest_emoji", { label }),
};

/* Types */
/**
 *  Full budget with records. Returned by get_budget / create_budget / update_budget.
 *  Only ever held in the store's `current` field (one budget at a time).
 */
export type BudgetDetail = {
	id: number,
	name: string,
	startDate: string,
	endDate: string,
	status: string,
	/**  Optional markdown note attached to this budget. NULL in DB maps to None. */
	notes: string | null,
	createdAt: string,
	records: BudgetRecord[],
};

export type BudgetRecord = {
	id: number,
	budgetId: number,
	type: string,
	emoji: string,
	label: string,
	amount: number,
	notes: string | null,
	/**
	 *  True when this record was created while the parent budget was in "needs review"
	 *  (active + strictly past end_date). Immutable — set once at creation.
	 */
	isAdjustment: boolean,
	tags: BudgetTag[],
};

/**
 *  Lightweight summary returned by list_budgets. Totals precomputed in SQL.
 *  No records — records only live in BudgetDetail for the one open budget.
 */
export type BudgetSummary = {
	id: number,
	name: string,
	startDate: string,
	endDate: string,
	status: string,
	createdAt: string,
	totalInflow: number,
	totalOutflow: number,
};

export type BudgetTag = {
	id: number,
	name: string,
	color: string,
};

/**
 *  A group of import records destined for one budget.
 *  `is_new` is true when no existing budget has this exact name.
 *  `start_date`/`end_date` are only used (and required) when `is_new` is true.
 */
export type CsvImportGroup = {
	budget: string,
	isNew: boolean,
	startDate: string | null,
	endDate: string | null,
	records: CsvImportRecord[],
};

/**
 *  Returned by `parse_csv_preview` — the groups the user reviews before confirming.
 *  `errors` contains row-level warnings for skipped rows (bad type, non-integer amount, etc.).
 */
export type CsvImportPreview = {
	groups: CsvImportGroup[],
	errors: string[],
};

/**  A single record parsed from an import CSV row. */
export type CsvImportRecord = {
	emoji: string,
	label: string,
	type: string,
	amount: number,
	tags: string[],
	notes: string | null,
};

/**  Returned by `import_groups` — summary of what was created. */
export type ImportResult = {
	budgetsCreated: number,
	recordsImported: number,
};

/**  Returned by `take_restore_status` once per restore attempt. */
export type RestoreOutcome = {
	ok: boolean,
	message: string,
};

/**  Filter sent by the Stats page to get_stats_summary. */
export type StatsFilter = {
	/**  AND-include: records must carry ALL of these tag ids. */
	tagIds: number[],
	/**  OR-exclude: records carrying ANY of these tag ids are dropped. */
	excludeTagIds: number[],
	/**  None = both types | Some("inflow") | Some("outflow") */
	recordType: string | null,
};

/**  Full aggregated stats summary returned to the Stats page. */
export type StatsSummary = {
	totalInflow: number,
	totalOutflow: number,
	/**  Number of records matching the filter. */
	matchCount: number,
	/**  Number of distinct budgets represented in the match set. */
	matchBudgets: number,
	/**  Inflow total keyed by budget lifecycle status. */
	inflowByStatus: { [key in string]: number },
	/**  Outflow total keyed by budget lifecycle status. */
	outflowByStatus: { [key in string]: number },
	/**
	 *  Per-tag breakdown of the FILTERED set, excluding the include-tags themselves
	 *  (co-occurrence view). Includes a synthetic "misc" entry (tag_id=0) for untagged records.
	 */
	byTag: TagStat[],
	/**
	 *  Tags present on the BASE set (type + include, before exclude step).
	 *  Drives the exclude-tag dropdown. Real tags only; no misc.
	 */
	baseTags: TagStat[],
};

/**  A record row carrying its parent budget's name. Returned by list_records_by_tag. */
export type TagRecord = {
	id: number,
	budgetId: number,
	budgetName: string,
	type: string,
	emoji: string,
	label: string,
	amount: number,
	isAdjustment: boolean,
};

/**  Aggregated stats for one tag within the filtered record set. */
export type TagStat = {
	tagId: number,
	tagName: string,
	tagColor: string,
	inflow: number,
	outflow: number,
};

export type TagWithUsage = {
	id: number,
	name: string,
	color: string,
	usageCount: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

